services:
  db_shortener:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: encurtador_db
    ports:
      - "7000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api_shortener:
    build: .
    container_name: spring_api
    ports:
      - "8080:8080"
    depends_on:
      - db_shortener

  pgadmin_shortener:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata: